export default {
  FETCH_STOCKS_REQUEST: 'FETCH_STOCKS_REQUEST',
  FETCH_STOCKS_SUCCESS: 'FETCH_STOCKS_SUCCESS',
  CHANGE_CURRENT_STOCK: 'CHANGE_CURRENT_STOCK',
  FETCH_SERIES_SUCCESS: 'FETCH_SERIES_SUCCESS',
  CHANGE_CURRENT_SERIE: 'CHANGE_CURRENT_SERIE',
  FETCH_CALL_OPTIONS_SUCCESS: 'FETCH_CALL_OPTIONS_SUCCESS',
  CHANGE_CAPITAL: 'CHANGE_CAPITAL',
  CHANGE_CALL_OPTION_SCORE: 'CHANGE_CALL_OPTION_SCORE',
  TRAIN_DATA_REQUEST: 'TRAIN_DATA_REQUEST',
  TRAIN_DATA_SUCCESS: 'TRAIN_DATA_SUCCESS'
}
